version: "3.9"

networks:
  app-net-wiki:
    driver: bridge

services:
  wiki:
    build: ./
    command: gunicorn base.wsgi:application --bind 0.0.0.0:1111
    volumes:
        - ./django-wiki/:/usr/src/app/
        # - static_volume:/usr/src/app/static
    networks:
      - app-net-wiki
    ports:
      - 1111:1111
    mem_limit: 512m
    mem_reservation: 256M
    env_file:
        - ./.env
    restart: unless-stopped
  
  # nginx:
  #   build: ./nginx
  #   networks:
  #     - app-net-wiki
  #   ports:
  #     - 1234:80
  #   depends_on:
  #     - wiki
  #   volumes:
  #       - static_volume:/usr/src/app/static
  
# volumes:
#   static_volume: